#! /bin/sh

sxhkd &
nm-applet &
xset +fp /usr/share/fonts/misc
xset +fp /usr/share/fonts/envypn
xset fp rehash &
# setxkbmap es &
compton --config ~/.config/compton/conf &
wal -i ~/wallpapers/wallhaven-549707.jpg
polybar -r top &
xmodmap ~/.xmodmap &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "$(xrdb -query | grep '*color2' | cut -f 2)"
bspc config ignore_ewmh_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a Firefox desktop='^1'
bspc rule -a pavucontrol state=floating follow=on

firefox &
